TRUNK-5810: Relationship Domain - Switching from Hibernate Mappings to Annotations
openmrs/openmrs-core pull request #3283
Opened 2020-06-30 12:25 UTC by alinmihaila99

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5810

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2020-07-01 07:53 UTC, HerbertYiga commented on api/src/main/java/org/openmrs/Relationship.java
> +
looks good though with some code formats,you could use mvn clean  package before pushing to git

2020-08-30 10:52 UTC, Ruhanga requested changes
@alinmihaila99, could you resolve the merge conflict on this PR.

2020-08-30 10:54 UTC, Ruhanga commented on api/src/main/java/org/openmrs/Relationship.java
>  	private Integer relationshipId;
@alinmihaila99, could you not plainly use `GenerationType.IDENTITY` as decided upon this earlier?

2020-09-03 06:03 UTC, Ruhanga approved these changes

2020-09-03 06:04 UTC, Ruhanga approved these changes

2021-06-14 00:13 UTC, closed without merging