TRUNK-5942 Adding curly braces to Control structures
openmrs/openmrs-core pull request #3527
Opened 2020-08-23 11:11 UTC by miirochristopher

## Added curly braces to Control Structures, removed spaces and corrected indentation. 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5942

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.
- [ ] I have **added tests** to cover my changes. 
- [ ] I ran `mvn clean package` right before creating this pull request and added all formatting changes to my commit.
- [ ] All new and existing **tests passed**.
- [ ] My pull request is **based on the latest changes** of the master branch.

2020-08-23 18:07 UTC, sherrif10 commented on api/src/main/java/org/openmrs/util/HandlerUtil.java
> +			}
Thanks @miirochristopher for working on this, could you remove some spaces, Also try to  do identation

2020-08-23 19:51 UTC, sacull requested changes

2020-08-23 19:51 UTC, sacull commented on api/src/main/java/org/openmrs/module/ModuleClassLoader.java
> +		{
For readability in Java, the brace "{" is on the same line as the previous line of code. If some people write on the same line, the other part in the new line, the code will become less readable.

2020-08-23 19:51 UTC, sacull commented on api/src/main/java/org/openmrs/module/ModuleClassLoader.java
> +				{
Same as above.

2020-08-23 19:51 UTC, sacull commented on api/src/main/java/org/openmrs/util/HandlerUtil.java
> +			{
Again same as above.

2020-08-24 00:09 UTC, miirochristopher commented
Thanks for the feedback @sherrif10 and @sacull. I made commits to correct the indentation and remove spaces.

2020-08-24 03:18 UTC, sacull commented
Great job, thanks @miirochristopher. When the PR is ready, it is worth informing about it in JIRA. To do this, use the "Request Code Review" button and add a link to this PR in the comment.

2020-08-24 06:38 UTC, HerbertYiga commented
@miirochristopher   you can go on and squash your commits

2020-08-24 07:22 UTC, sacull approved these changes

2020-08-24 07:26 UTC, sacull commented
@miirochristopher If you need help with splash commits mentioned by @HerbertYiga: https://wiki.openmrs.org/display/docs/Git-Squashing+commits

2020-08-24 09:16 UTC, dkayiwa commented
@HerbertYiga have you ever seen this? https://talk.openmrs.org/t/rfc-favour-not-squashing-commits-over-squashing-commits/28482

2020-08-24 09:16 UTC, miirochristopher commented
@sacull and @HerbertYiga , squashing done, thanks!

2020-08-24 09:43 UTC, sherrif10 commented
@miirochristopher  did you see travis ci ?

2020-08-24 09:47 UTC, miirochristopher commented
@sherrif10 , No I did not.

2020-08-24 09:48 UTC, dkayiwa commented
The travis build failure is caused by something else. Am looking into it.

2020-08-24 09:50 UTC, sherrif10 commented
@dkayiwa  great thanks

2020-08-25 06:58 UTC, mozzy11 commented
@sherrif10 , @dkayiwa .
  i rebuilt the travis Build and it passed.
 had't looked at the actual cause of the innitial build failure

2020-08-25 09:30 UTC, sherrif10 approved these changes

2020-08-25 13:32 UTC, dkayiwa commented
@sacull do you approve this? 😊

2020-08-25 14:25 UTC, sacull approved these changes

2020-08-25 14:27 UTC, sacull commented
@dkayiwa Well, now my ego has grown since you ask me for my opinion. ;)

2020-08-25 14:27 UTC, merged

2020-08-25 14:28 UTC, sacull commented
@miirochristopher For the next PR, please remember about the checklist you have in the PR description.

2020-08-25 14:28 UTC, dkayiwa commented
You deserve it man!!! 😊 👍

2020-08-25 15:01 UTC, mozzy11 commented
hahah 😊  👍

2020-08-26 18:00 UTC, miirochristopher commented
Thanks @sacull  @dkayiwa  @mozzy11 @HerbertYiga @sherrif10 ....That got me going. Gotta try to keep out the smoke on the next PR,  :+1: :+1: :)