TRUNK-5115-new1:Replace use of conditional logging with slf4j paramet…
openmrs/openmrs-core pull request #3552
Opened 2020-09-01 10:17 UTC by gracebish

…erized messages

**Pull request title**
TRUNK-5115-new1:Replace use of conditional logging with slf4j parameterized messages

****Issue worked on**
TRUNK-5115-new1:Replace use of conditional logging with slf4j parameterized messages

**Description of what I changed**
Replace use of conditionals which are aimed at preventing to construct the debug message with slf4js parametrized messages

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-

## Checklist: I completed these to help reviewers :)

- [ x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2020-09-02 10:03 UTC, gracebish commented
@teleivo , kindly review and advise accordingly

2020-09-05 14:44 UTC, achilep commented
https://github.com/openmrs/openmrs-core/search?p=1&q=log.isDebugEnabled%28%29&unscoped_q=log.isDebugEnabled%28%29
 this is all the occurrence of 

```
if (log.isDebugEnabled()) {
 log.debug("Creating observations for message " + messageControlId + "...");
}
```
 thanks @gracebish

2020-09-11 12:47 UTC, HerbertYiga commented
Hi @ibacher  is this good for merging?  @dkayiwa

2020-09-12 05:00 UTC, sacull requested changes

2020-09-12 05:00 UTC, sacull commented on api/src/main/java/org/openmrs/scheduler/TaskFactory.java
> +				log.debug("Error creating new task for class {}", taskDefinition.getTaskClass(), e);
Aren't you one tab too many here?
![image](https://user-images.githubusercontent.com/9057882/92987732-88dad980-f4c5-11ea-850a-a50c7bc99a35.png)

2020-09-12 17:11 UTC, gracebish commented
Thank @Lucasz Debicki for the review. Please advise before i make the
changes. The original code is like https://snipboard.io/ZJThIo.jpg
If i move one tab back, won't it create some code spacing problem?

On Sat, Sep 12, 2020 at 8:00 AM Łukasz Dębicki <notifications@github.com>
wrote:

> *@sacull* requested changes on this pull request.
> ------------------------------
>
> In api/src/main/java/org/openmrs/scheduler/TaskFactory.java
> <https://github.com/openmrs/openmrs-core/pull/3552#discussion_r487368665>:
>
> >  				// don't need to log errors here necessarily.  If its needed, the calling method can log it.
> -				log.debug("Error creating new task for class " + taskDefinition.getTaskClass(), e);
> -			}
> +				log.debug("Error creating new task for class {}", taskDefinition.getTaskClass(), e);
>
> Aren't you one tab too many here?
> [image: image]
> <https://user-images.githubusercontent.com/9057882/92987732-88dad980-f4c5-11ea-850a-a50c7bc99a35.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/3552#pullrequestreview-487203851>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOPD5MHLNAYROETO7JYS2J3SFL57TANCNFSM4QRRKPVQ>
> .
>

2020-09-12 20:17 UTC, sacull commented
In my opinion, removing the red tabs will make spacing perfect. ;)
![image](https://user-images.githubusercontent.com/9057882/93004235-7bfdca80-f545-11ea-803f-c7c51b8ca4a7.png)

2020-09-13 14:55 UTC, ibacher reviewed
@gracebish A few small things need to be fixed, but otherwise, I think this is fine to merge.

2020-09-13 14:55 UTC, ibacher commented on web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java
> +		log.debug("sending error: {} []", error, message);
```suggestion
		log.debug("sending error: {} [{}]", error, message);
```

Otherwise, the message is excluded from the log message.

2020-09-13 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/api/db/hibernate/HibernateContextDAO.java
> +			log.debug("Registering session with synchronization manager ({})", sessionFactory.hashCode());
Any reason to skip the logging message in the `if` block above?

2020-09-13 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/scheduler/TaskFactory.java
> +				log.debug("Error creating new task for class {}", taskDefinition.getTaskClass(), e);
```suggestion
			log.debug("Error creating new task for class {}", taskDefinition.getTaskClass(), e);
```

This is identical to @sacull's comment above.

2020-10-11 22:39 UTC, gracebish commented
I have made one more commit. Kindly review and advise then i can squash my commits

2020-10-12 03:18 UTC, sacull requested changes

2020-10-12 03:18 UTC, sacull commented on web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java
> +		log.debug("sending error: {} []", error, message);
```suggestion
		log.debug("sending error: {} [{}]", error, message);
```
You still have a problem here.

2020-10-12 05:55 UTC, gracebish commented
Thanks for the quick review. I made the change as in https://snipboard.io/jlusg6.jpg. I am just astounded as to why the changes are not appearing and the asterisk on the same file yet all other changes were reflected in the other files i worked on. Kindly advise

2020-10-12 09:25 UTC, sacull commented
https://github.com/gracebish/openmrs-core/blob/TRUNK-5115-new1/web/src/main/java/org/openmrs/web/filter/GZIPResponseWrapper.java#L114

Are you sure you sent the changes to the remote repository?

2020-10-12 20:12 UTC, gracebish commented
I will close this PR and work afresh on the same issue

2020-10-12 20:12 UTC, closed without merging