Adding commas in config files
openmrs/openmrs-core pull request #4190
Opened 2022-11-14 22:21 UTC by Tanga-Jonathan

Below is my ticket url
I have placed commas in the config files 1.5.dtd and 1.6.dtd

https://issues.openmrs.org/browse/TRUNK-6142

2022-11-19 20:52 UTC, ryanmccauley211 requested changes
The added commas look good, it is just additional formatting that needs to be reverted please

2022-11-19 20:52 UTC, ryanmccauley211 commented on api/src/main/resources/org/openmrs/module/dtd/config-1.5.dtd
> +(id),
The indentation has been removed in this file, can you revert this please. I think the diff should only show the lines where the commas were added.

2022-11-19 20:52 UTC, ryanmccauley211 commented on api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd
> +Top level configuration element.
Same with this file, please revert the removed indentation and leave only the added commas

2022-11-20 02:30 UTC, Tanga-Jonathan commented
Okay, thank you let me put back the indentation the way it was

On Sat, 19 Nov 2022, 23:52 Ryan McCauley, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The added commas look good, it is just additional formatting that needs to
> be reverted please
> ------------------------------
>
> In api/src/main/resources/org/openmrs/module/dtd/config-1.5.dtd
> <https://github.com/openmrs/openmrs-core/pull/4190#discussion_r1027141429>
> :
>
> > -	<!ELEMENT param-value (#PCDATA)>
> -
> -	<!ELEMENT filter-mapping (filter-name, (url-pattern | servlet-name))>
> -	<!ELEMENT url-pattern (#PCDATA)>
> -
> -	<!ELEMENT messages (lang, file)>
> -	<!ELEMENT lang (#PCDATA)>
> -	<!ELEMENT file (#PCDATA)>
> -
> -	<!ELEMENT mappingFiles (#PCDATA)>
> -	<!ELEMENT packagesWithMappedClasses (#PCDATA)>
> +<!--
> +Top level configuration element.
> +-->
> +<!ELEMENT module (
> +(id),
>
> The indentation has been removed in this file, can you revert this please.
> I think the diff should only show the lines where the commas were added.
> ------------------------------
>
> In api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd
> <https://github.com/openmrs/openmrs-core/pull/4190#discussion_r1027141513>
> :
>
> > -
> -	<!ELEMENT messages (lang, file)>
> -	<!ELEMENT lang (#PCDATA)>
> -	<!ELEMENT file (#PCDATA)>
> -
> -	<!ELEMENT mappingFiles (#PCDATA)>
> -	<!ELEMENT packagesWithMappedClasses (#PCDATA)>
> -	
> -	<!ELEMENT conditionalResources (conditionalResource+)>
> -	<!ELEMENT conditionalResource (path, (openmrsVersion | loadIfModulesPresent))>
> -	<!ELEMENT path (#PCDATA)>
> -	<!ELEMENT openmrsVersion (#PCDATA)>
> -	<!ELEMENT loadIfModulesPresent (openmrsModule+)>
> -	<!ELEMENT openmrsModule (moduleId, version)>
> -	<!ELEMENT moduleId (#PCDATA)>
> +Top level configuration element.
>
> Same with this file, please revert the removed indentation and leave only
> the added commas
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/openmrs/openmrs-core/pull/4190#pullrequestreview-1187119413>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQGAEUJHO3RVGIS6ZTCEUL3WJE4XXANCNFSM6AAAAAASAJOIRQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-20 03:29 UTC, Tanga-Jonathan commented
I have worked on the indentation, if the changes are applicable please let
me know, and am requesting for a merge
On Sun, 20 Nov 2022, 05:30 TANGA JONATHAN, ***@***.***>
wrote:

> Okay, thank you let me put back the indentation the way it was
>
> On Sat, 19 Nov 2022, 23:52 Ryan McCauley, ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> The added commas look good, it is just additional formatting that needs
>> to be reverted please
>> ------------------------------
>>
>> In api/src/main/resources/org/openmrs/module/dtd/config-1.5.dtd
>> <https://github.com/openmrs/openmrs-core/pull/4190#discussion_r1027141429>
>> :
>>
>> > -	<!ELEMENT param-value (#PCDATA)>
>> -
>> -	<!ELEMENT filter-mapping (filter-name, (url-pattern | servlet-name))>
>> -	<!ELEMENT url-pattern (#PCDATA)>
>> -
>> -	<!ELEMENT messages (lang, file)>
>> -	<!ELEMENT lang (#PCDATA)>
>> -	<!ELEMENT file (#PCDATA)>
>> -
>> -	<!ELEMENT mappingFiles (#PCDATA)>
>> -	<!ELEMENT packagesWithMappedClasses (#PCDATA)>
>> +<!--
>> +Top level configuration element.
>> +-->
>> +<!ELEMENT module (
>> +(id),
>>
>> The indentation has been removed in this file, can you revert this
>> please. I think the diff should only show the lines where the commas were
>> added.
>> ------------------------------
>>
>> In api/src/main/resources/org/openmrs/module/dtd/config-1.6.dtd
>> <https://github.com/openmrs/openmrs-core/pull/4190#discussion_r1027141513>
>> :
>>
>> > -
>> -	<!ELEMENT messages (lang, file)>
>> -	<!ELEMENT lang (#PCDATA)>
>> -	<!ELEMENT file (#PCDATA)>
>> -
>> -	<!ELEMENT mappingFiles (#PCDATA)>
>> -	<!ELEMENT packagesWithMappedClasses (#PCDATA)>
>> -	
>> -	<!ELEMENT conditionalResources (conditionalResource+)>
>> -	<!ELEMENT conditionalResource (path, (openmrsVersion | loadIfModulesPresent))>
>> -	<!ELEMENT path (#PCDATA)>
>> -	<!ELEMENT openmrsVersion (#PCDATA)>
>> -	<!ELEMENT loadIfModulesPresent (openmrsModule+)>
>> -	<!ELEMENT openmrsModule (moduleId, version)>
>> -	<!ELEMENT moduleId (#PCDATA)>
>> +Top level configuration element.
>>
>> Same with this file, please revert the removed indentation and leave only
>> the added commas
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/openmrs/openmrs-core/pull/4190#pullrequestreview-1187119413>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AQGAEUJHO3RVGIS6ZTCEUL3WJE4XXANCNFSM6AAAAAASAJOIRQ>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2022-11-20 12:06 UTC, ryanmccauley211 approved these changes
LGTM - I also tested it locally and it fixes the new dtd tests I am trying to add

2022-11-20 16:48 UTC, Tanga-Jonathan commented
Hello @dkayiwa am requesting that you look through, thank you

2023-02-01 04:41 UTC, wikumChamith requested changes
Change the topic of PR like this `TRUNK-6142 : Adding commas in config files`. Also, squash your commits into one. Can you have  look at this? https://wiki.openmrs.org/display/docs/Pull+Request+Tips

2023-02-23 22:29 UTC, dkayiwa commented
It looks like this is already done here: https://github.com/openmrs/openmrs-core/commit/c1a84dd7bdc98ad83b7acfb23006ad3115330558

2023-02-23 22:29 UTC, closed without merging