(fix)TRUNK-7521:Complex obs valueComplex should be more robust to Str…
openmrs/openmrs-core pull request #4285
Opened 2023-03-24 08:42 UTC by jona42-ui

…ing#split

TRUNK-5721: Complex obs valueComplex should be more robust to String#split

## Description of what I changed
Added a null check to ensure that the file variable is not null before attempting to read its contents:
This will return the original obs object if the file is null, rather than attempting to construct a ComplexData object from a null file and throwing a NullPointerException.

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5721

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.
- [x] All new and existing **tests passed**.
- [x] My pull request is **based on the latest changes** of the master branch.

2023-03-24 08:43 UTC, jona42-ui commented
cc/ @dkayiwa @

2023-03-24 10:17 UTC, mks-d reviewed
This should most likely come with test case(s) that clearly illustrate the [given/when/then](https://www.newthings.co/blog/structuring-tests-using-given-when-then/) of what is intended here.

2023-03-24 11:55 UTC, jona42-ui commented
great, thanks @mks-d on  my radar, next week

2023-03-24 15:41 UTC, ibacher commented
I'm not sure I see how this actually addresses the NPEs mentioned in the ticket...

2023-03-29 04:43 UTC, jona42-ui commented
@ibacher does this handle all NPEs you woul xpect such that I can do test cases for the scenarios?

2023-03-29 17:00 UTC, ibacher commented
Do you have test cases as @mks-d suggested? It looks like this handles some NPEs; I'm not convinced that the `IllegalArgumentException`s are a good idea, though...

2023-03-30 07:48 UTC, jona42-ui commented
> Do you have test cases as @mks-d suggested? It looks like this handles some NPEs; I'm not convinced that the `IllegalArgumentException`s are a good idea, though...

sure, still fighting with error handling in test cases.
sure, i may not be 100% certain of suitability of IllegalArgumentExceptions but i provided it to quickly catch errors.  A more  optimised exception handler would be glad to use.

2023-04-12 14:55 UTC, ibacher requested changes

2023-04-12 14:55 UTC, ibacher commented on api/mytxtfile.txt
> +test content
Test data always goes in `src/test` (and then an appropriate sub-directory.

2023-04-12 14:55 UTC, ibacher commented on api/pom.xml
> +		<dependency>
The API project should not depend on spring-web

2023-04-12 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/obs/ComplexData.java
> +	public ComplexData(String fILENAME, Object data) {
I'm not sure why this parameter needs to be renamed. ComplexData can store more than just files, though one use of this field is for filenames.

2023-04-12 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/obs/ComplexData.java
> +	public File[] getFiles() {
We shouldn't need this...

2023-04-12 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/obs/handler/AbstractHandler.java
> +	public Obs getObs(Obs obs, String fILENAME) {
This change is also unnecessary...

2023-04-12 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/obs/handler/BinaryDataHandler.java
> +		if (file == null) {
Probably should check if the obs is null too right?

2023-04-12 14:55 UTC, ibacher commented on api/src/main/java/org/openmrs/obs/handler/BinaryDataHandler.java
> +			String originalFilename =  (names.length > 0) ? names[0] : "";
The parentheses here are unnecessary.

2023-04-12 14:55 UTC, ibacher commented on api/src/test/java/org/openmrs/obs/AbstractHandlerTest.java
> +	private Obs obs;
It's better not to introduce a class-level variable in tests where it can be avoided.

2023-04-12 14:55 UTC, ibacher commented on api/src/test/java/org/openmrs/test/jupiter/BaseContextSensitiveTest.java
> +	public static final Logger log = LoggerFactory.getLogger(BaseContextSensitiveTest.class);
Please don't change this visibility if you need a logger in your test, create a class-specific version.

2023-05-04 13:35 UTC, jona42-ui commented
sorry, have to clean this up

2023-05-04 13:37 UTC, jona42-ui commented
un intended!!

2023-11-01 00:28 UTC, closed without merging