TRUNK-6180: Add locale to context after authentication.
openmrs/openmrs-core pull request #4324
Opened 2023-05-15 08:19 UTC by icrc-loliveira

## Description of what I changed

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-6180

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2023-05-15 09:24 UTC, tendomart commented on api/src/test/java/org/openmrs/api/UserServiceTest.java
> +
do you have to declare the  Context object several times.

2023-05-15 09:26 UTC, tendomart commented
always try running "mvn clean package" before committing.

you have some issues here at

```
Error:    UserServiceTest.saveUserProperties_shouldRemoveAllExistingPropertiesAndAssignNewProperties:1297 expected: <1> but was: <2>
Error:    UserServiceTest.saveUserProperty_shouldAddNewPropertyToExistingUserProperties:1278 expected: <1> but was: <2>
```

2023-05-15 14:08 UTC, ibacher requested changes
Thanks @icrc-loliveira! One small adjustment, I think but should be G2G

2023-05-15 14:31 UTC, ibacher approved these changes

2023-05-15 15:09 UTC, ibacher commented
@icrc-loliveira Could you try rebasing this on the latest version of master? I think we have a fix for the failing tests.

2023-05-15 16:04 UTC, icrc-loliveira commented
Done

2023-05-16 15:55 UTC, ibacher commented on api/src/test/resources/org/openmrs/api/include/UserServiceTest.xml
> +
```suggestion
```

2023-05-16 15:56 UTC, merged