TRUNK-6185: Easier configuration of csrfguard.properties
openmrs/openmrs-core pull request #4369
Opened 2023-08-19 06:11 UTC by wikumChamith

## Description of what I changed

This commit updates the loadCsrfGuardProperties method to enhance the loading of CSRF Guard properties. It first checks for the existence of the csrfguard.properties file in the `.OpenMRS` directory. If the file exists, its contents are loaded. Otherwise, the default values are loaded from the `/WEB-INF/csrfguard.properties` file. Additionally, properties starting with `org.owasp.csrfguard` from `openmrs-runtime.properties` are merged into the loaded properties. 

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-6185

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2023-08-21 12:53 UTC, mseaton requested changes

2023-08-21 14:15 UTC, wikumChamith commented
@mseaton I addressed the issues you pointed out.

2023-08-21 15:12 UTC, mseaton commented
@wikumChamith , no this doesn't look right.  You shouldn't be putting logic into the catch block, and you still don't have any finally blocks where you close the input streams.

2023-08-22 18:53 UTC, ibacher commented on web/src/main/java/org/openmrs/web/Listener.java
> +			try {
Doesn't seem right to do this _unconditionally_ in the catch block. There are numerous reasons an `IOException` could be thrown above, but only one where we'd want to fallback: a `FileNotFound` exception. On top of which, the error here is always swallowed.

2023-08-22 18:53 UTC, ibacher commented on web/src/main/java/org/openmrs/web/Listener.java
> +				ioException1.printStackTrace();
Log, rather than printing.

2023-08-22 18:53 UTC, ibacher commented on web/src/main/java/org/openmrs/web/Listener.java
> +		Properties runtimeProperties = OpenmrsUtil.getRuntimeProperties(WebConstants.WEBAPP_NAME);
It's preferable to use `Context.getRuntimeProperties()`

2023-08-22 18:53 UTC, ibacher commented on web/src/main/java/org/openmrs/web/Listener.java
> +		IOUtils.closeQuietly(csrfGuardInputStream);
This really needs to be done in a finally block. There are way to many ways an exception can be thrown in the above code and so the IO stream never closed.

2023-08-22 18:53 UTC, ibacher commented on web/src/main/java/org/openmrs/web/Listener.java
> +	private void loadCsrfGuardProperties(ServletContext servletContext) throws IOException {
Note that `loadCsrfGuardProperties()` is currently called _before_ the runtime properties are setup, which means `OpenmrsUtil.getApplicationDirectory()` (inter alia) can return the wrong folder. Ideally, this call should be moved to after the runtime properties are loaded.

2023-08-24 10:39 UTC, wikumChamith commented
@mseaton, @ibacher I refactored the code according to your feedback.

2023-08-24 12:57 UTC, mseaton requested changes
Looking much better - a few additional comments to consider.

2023-08-24 12:57 UTC, mseaton commented on web/src/main/java/org/openmrs/web/Listener.java
> +				log.error(e.getMessage());
I'm not sure about just logging an error here and continuing.  Why catch this Exception if you aren't going to fall back to other behavior?  If we want to log this here (which is probably a good idea), then I'd add some additional context in the logging message to make it easier for someone to know where the problem is and what went wrong, and then re-throw the Exception.

2023-08-24 12:57 UTC, mseaton commented on web/src/main/java/org/openmrs/web/Listener.java
> +				log.error(e.getMessage());
Same comment here.  Just log, with a more helpful message for implementers to better understand the error, and then re-throw the Exception

2023-08-24 12:57 UTC, mseaton commented on web/src/main/java/org/openmrs/web/Listener.java
> +			if(property.startsWith("org.owasp.csrfguard")) {
Style comment - please put a space between the `if` and the `(`.  Apply this elsewhere in this PR as well.

2023-08-25 02:10 UTC, wikumChamith commented
@mseaton I addressed the issues you pointed out. Please review the new code.

2023-08-25 13:59 UTC, mseaton reviewed
Just a few minor style comments @wikumChamith and then I think it looks good.  The only other thing that I'd love to see are some unit tests around this, if this is possible to do.  Not sure if @ibacher has any additional feedback.

2023-08-25 15:38 UTC, wikumChamith commented
@mseaton I addressed the suggestions you made. Any suggestions on a viable way that I can write tests for this method?

2023-08-25 16:46 UTC, mseaton approved these changes

2023-08-25 16:48 UTC, merged