TRUNK-5952: Order validation is bypassed if certain fields are set from the OrderContext.
openmrs/openmrs-core pull request #4581
Opened 2024-03-11 17:17 UTC by IamMujuziMoses

## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5952

## Checklist: I completed these to help reviewers :)

- [ ] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [ ] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [ ] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [ ] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [ ] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2024-03-11 17:56 UTC, IamMujuziMoses commented
@mseaton  @dkayiwa @ibacher could you please review this PR

2025-11-07 17:17 UTC, mseaton commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +	private void validateFieldsForOrderContextOutPatientCareSettingType(Order order, OrderContext orderContext) {
I don't really like that this duplicates validation logic already happening elsewhere (and would need to be kept consistent with it), or that this is limited to this very specific issue that was discovered in the ticket.

My suggestion in the ticket was to try invoking the validator in the saveOrderInternal method, before saving with the DAO.  Would be good to know if this was attempted or not and if it caused problems, or otherwise why that approach was not taken?

2025-11-07 17:17 UTC, mseaton requested changes
See comment

2025-11-09 22:44 UTC, mseaton approved these changes
This looks ok to me, though see my comment.  @dkayiwa thoughts?

2025-11-09 22:44 UTC, mseaton commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
I don't think we necessarily need this restriction.

2025-11-10 07:22 UTC, IamMujuziMoses commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
Running validation unconditionally breaks existing behaviour/tests that never received post-validation before. Therefore we need to guard with orderContext != null so that this new validation only applies to the code paths where an OrderContext is actually provided and expected

2025-11-10 11:13 UTC, mseaton commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
What tests does it break?  Do the tests seem correct and do the new failures look like they are exposing additional bugs?  Can you be more specific?

2025-11-10 11:30 UTC, IamMujuziMoses commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
The tests seem correct:
```stacktrace
org.opentest4j.AssertionFailedError: expected: java.util.Date@4c92384f<Mon Nov 10 14:20:07 EAT 2025> but was: java.util.Date@543e126<Mon Nov 10 14:20:07 EAT 2025>
Expected :Mon Nov 10 14:20:07 EAT 2025
Actual   :Mon Nov 10 14:20:07 EAT 2025
```
Just  a classic Java Date object equality vs. value equality issue in tests that happens even though the two Date objects print exactly the same

2025-11-10 11:33 UTC, mseaton commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
Are you sure?  `Sun Nov 09 15:16:07 EAT 2025` does not look the same as 1`Mon Nov 10 14:20:07 EAT 2025`,  Not sure what the "Expected" and "Actual" methods look like that.  But the assertion failure message shows differences.  Point is - if the test is failing in a situation where it should not be failing, let's figure out why and fix it and remove that unnecessary constraint on orderContext != null.

2025-11-11 08:34 UTC, IamMujuziMoses commented on api/src/main/java/org/openmrs/api/impl/OrderServiceImpl.java
> +		if (orderContext != null) {
I think that the ```orderContext != null``` check scopes the fix to the path where this inconsistency actually occurs, saveOrder(Order, OrderContext). without it, we’d start running post-validation on legacy calls that never had it, causing unrelated test failures and changing existing behavior, this keeps the fix focused on the API scenario described in the ticket, preventiing Order validation from being bypassed if certain fields are set from the OrderContext.

2026-05-11 01:49 UTC, closed without merging