(chore) O3-3551: Use latest Actions in GH Actions
openmrs/openmrs-core pull request #4690
Opened 2024-07-14 04:18 UTC by Bcoderx6

https://openmrs.atlassian.net/browse/O3-3551

This PR updates several GitHub Actions to their latest versions for improved performance, security, and compatibility.

Changes:
- Updated `actions/checkout` from `v4` to `v4.1.7`
- Updated `actions/setup-java` from `v4` to `v4.2.1`
- Updated `actions/cache` from `v4` to `v4.0.2`
- Updated `actions/upload-artifact` from `v4` to `v4.3.4`

These updates ensure we are using the most recent enhancements and fixes provided by the maintainers.

2024-07-14 04:19 UTC, Bcoderx6 commented
@jayasanka-sack !

2024-07-15 10:18 UTC, jayasanka-sack requested changes
Thanks for the PR @Bcoderx6 ! Please check the comment below.

2024-07-15 10:18 UTC, jayasanka-sack commented on .github/workflows/build-2.x.yaml
> +      - uses: actions/checkout@v4.1.7
```suggestion
      - uses: actions/checkout@v4
```
Using `@v4` will automatically use the latest minor and patch version within the v4 major version series.

2024-07-16 13:51 UTC, Bcoderx6 commented
@jayasanka-sack ! can u check now i fixed it

2024-07-17 09:56 UTC, jayasanka-sack commented on .github/workflows/build-2.x.yaml
> +      - uses: actions/checkout@v4.1.7
@Bcoderx6 this comment applies to all other places in this file.

2024-07-18 10:22 UTC, jayasanka-sack commented
@Bcoderx6 check this comment: https://github.com/openmrs/openmrs-core/pull/4690#discussion_r1680776206

2024-07-18 11:39 UTC, Bcoderx6 commented
@jayasanka-sack !

2024-07-18 16:13 UTC, jayasanka-sack approved these changes
Thanks @Bcoderx6!

2024-07-18 16:13 UTC, merged