TRUNK-5918 : Switching from Hibernate Mappings to Annotations for ConceptName Domain
openmrs/openmrs-core pull request #4879
Opened 2024-12-27 16:19 UTC by UNCANNY69

Switching from Hibernate Mappings to Annotations for ConceptName Domain.

## Description of what I changed

Switched the Hibernate Mappings to Annotations for ConceptName Domain.
## Issue I worked on

see https://issues.openmrs.org/browse/TRUNK-5918

## Checklist: I completed these to help reviewers :)

- [x] My IDE is configured to follow the [**code style**](https://wiki.openmrs.org/display/docs/Java+Conventions) of this project.

  No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes. (If you refactored
  existing code that was well tested you do not have to add tests)

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] I ran `mvn clean package` right before creating this pull request and
  added all formatting changes to my commit.

  No? -> execute above command

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the master branch.

  No? Unsure? -> execute command `git pull --rebase upstream master`

2024-12-27 18:34 UTC, ManojLL requested changes

2024-12-27 18:34 UTC, ManojLL commented on api/src/main/java/org/openmrs/ConceptName.java
> -
add a line break

2024-12-27 18:34 UTC, ManojLL commented on api/src/main/java/org/openmrs/ConceptName.java
> +})
```suggestion
@AttributeOverrides({
        @AttributeOverride(name = "uuid", column = @Column(name = "uuid", length = 38, unique = true))
})
```

2025-03-30 04:57 UTC, rishabhrawat05 requested changes
Please change the highlighted sections

2025-03-30 04:57 UTC, rishabhrawat05 commented on api/src/main/java/org/openmrs/ConceptName.java
> +	@JoinColumn(name = "concept_id",nullable = false)
```suggestion
	@JoinColumn(name = "concept_id", nullable = false)
```

2025-03-30 04:57 UTC, rishabhrawat05 commented on api/src/main/java/org/openmrs/ConceptName.java
> +	@Column(name = "name",nullable = false)
```suggestion
	@Column(name = "name", nullable = false)
```

2025-03-30 04:57 UTC, rishabhrawat05 commented on api/src/main/java/org/openmrs/ConceptName.java
> +	@GeneratedValue(strategy = GenerationType.IDENTITY)
```suggestion
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "concept_name_seq")
    @SequenceGenerator(name = "concept_name_seq", sequenceName = "concept_name_concept_name_id_seq")
```

2025-05-26 13:41 UTC, dkayiwa commented
@UNCANNY69 are you still working on this?

2025-08-27 22:48 UTC, dkayiwa commented
@jayg2002 are you still working on this?

2025-08-28 17:38 UTC, jayg2002 commented
> @jayg2002 are you still working on this?

Hi @dkayiwa sorry i was not able to finish it but i feel at this point this would be a good beginner issue thus i will be closing the PR so new members of the community can attempt this.

2025-08-28 17:38 UTC, closed without merging